[I 12:44:18.229 NotebookApp] [nb_conda_kernels] enabled, 12 kernels found
[I 12:44:19.053 NotebookApp] Authentication of /metrics is OFF, since other authentication is disabled.
[W 12:44:23.950 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[W 2023-02-23 12:44:31.572 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
[W 2023-02-23 12:44:31.606 LabApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-02-23 12:44:31.606 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-02-23 12:44:31.606 LabApp] 'token' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-02-23 12:44:31.606 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-02-23 12:44:31.606 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-02-23 12:44:31.606 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-02-23 12:44:31.616 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
[W 2023-02-23 12:44:31.707 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
[I 2023-02-23 12:44:31.782 LabApp] JupyterLab extension loaded from /om/user/leokoz8/envs/add_RL/lib/python3.8/site-packages/jupyterlab
[I 2023-02-23 12:44:31.783 LabApp] JupyterLab application directory is /om/user/leokoz8/envs/add_RL/share/jupyter/lab
[I 12:44:31.837 NotebookApp] Serving notebooks from local directory: /rdma/vast-rdma/vast/fiete/leokoz8/code/add_RL
[I 12:44:31.837 NotebookApp] Jupyter Notebook 6.3.0 is running at:
[I 12:44:31.837 NotebookApp] http://node059:9000/
[I 12:44:31.838 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 12:48:01.495 NotebookApp] 302 GET / (172.16.24.254) 67.960000ms
/om/user/leokoz8/envs/add_RL/lib/python3.8/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[W 12:49:26.461 NotebookApp] Notebook notebooks/test_nb.ipynb is not trusted
Exception in callback <TaskStepMethWrapper object at 0x2b238e91bd60>()
handle: <Handle <TaskStepMethWrapper object at 0x2b238e91bd60>()>
Traceback (most recent call last):
  File "/om/user/leokoz8/envs/add_RL/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-38' coro=<RequestHandler._execute() running at /om/user/leokoz8/envs/add_RL/lib/python3.8/site-packages/tornado/web.py:1665> cb=[_HandlerDelegate.execute.<locals>.<lambda>() at /om/user/leokoz8/envs/add_RL/lib/python3.8/site-packages/tornado/web.py:2361]> while another task <Task pending name='Task-37' coro=<MappingKernelManager.start_kernel() running at /om/user/leokoz8/envs/add_RL/lib/python3.8/site-packages/notebook/services/kernels/kernelmanager.py:176> cb=[IOLoop.add_future.<locals>.<lambda>() at /om/user/leokoz8/envs/add_RL/lib/python3.8/site-packages/tornado/ioloop.py:687]> is being executed.
/om/user/leokoz8/envs/add_RL/lib/python3.8/site-packages/traitlets/traitlets.py:582: RuntimeWarning: coroutine 'RequestHandler._execute' was never awaited
  old_value = obj._trait_values[self.name]
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-38' coro=<RequestHandler._execute() running at /om/user/leokoz8/envs/add_RL/lib/python3.8/site-packages/tornado/web.py:1665> cb=[_HandlerDelegate.execute.<locals>.<lambda>() at /om/user/leokoz8/envs/add_RL/lib/python3.8/site-packages/tornado/web.py:2361]>
[I 12:49:28.362 NotebookApp] Kernel started: 79ab9147-4f39-43a8-9777-b51b91908188, name: conda-env-leokoz8-add_RL-py
/om/user/leokoz8/envs/add_RL/lib/python3.8/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[I 12:55:31.569 NotebookApp] Saving file at /notebooks/test_nb.ipynb
[W 12:55:31.574 NotebookApp] Notebook notebooks/test_nb.ipynb is not trusted
[I 12:57:30.365 NotebookApp] Saving file at /notebooks/test_nb.ipynb
[W 12:57:30.370 NotebookApp] Notebook notebooks/test_nb.ipynb is not trusted
[I 12:59:30.803 NotebookApp] Saving file at /notebooks/test_nb.ipynb
[W 12:59:30.809 NotebookApp] Notebook notebooks/test_nb.ipynb is not trusted
[I 13:01:30.841 NotebookApp] Saving file at /notebooks/test_nb.ipynb
[W 13:01:30.852 NotebookApp] Notebook notebooks/test_nb.ipynb is not trusted
[I 13:03:30.271 NotebookApp] Saving file at /notebooks/test_nb.ipynb
[W 13:03:30.276 NotebookApp] Notebook notebooks/test_nb.ipynb is not trusted
[I 13:05:06.233 NotebookApp] Saving file at /notebooks/test_nb.ipynb
[W 13:05:06.238 NotebookApp] Notebook notebooks/test_nb.ipynb is not trusted
[I 13:05:29.317 NotebookApp] Saving file at /notebooks/test_nb.ipynb
[W 13:05:29.323 NotebookApp] Notebook notebooks/test_nb.ipynb is not trusted
[I 13:07:29.675 NotebookApp] Saving file at /notebooks/test_nb.ipynb
[W 13:07:29.681 NotebookApp] Notebook notebooks/test_nb.ipynb is not trusted
[I 13:09:29.000 NotebookApp] Saving file at /notebooks/test_nb.ipynb
[W 13:09:29.004 NotebookApp] Notebook notebooks/test_nb.ipynb is not trusted
[I 13:11:29.684 NotebookApp] Saving file at /notebooks/test_nb.ipynb
[W 13:11:29.689 NotebookApp] Notebook notebooks/test_nb.ipynb is not trusted
[I 13:13:29.722 NotebookApp] Saving file at /notebooks/test_nb.ipynb
[W 13:13:29.727 NotebookApp] Notebook notebooks/test_nb.ipynb is not trusted
[I 00:06:21.037 NotebookApp] Starting buffering for 79ab9147-4f39-43a8-9777-b51b91908188:c6d8eebb81db41cfbc3099c7f7f8169a
slurmstepd: error: *** JOB 29504839 ON node059 CANCELLED AT 2023-02-24T00:43:55 DUE TO TIME LIMIT ***
